"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "chrisandkatiedotnet"
# Set this to today's date
compatibility_date = "2026-02-22"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[[d1_databases]]
binding = "DB"
database_name = "prisma-demo-db"
database_id = "73260722-51d9-4a90-961e-00d066b5dbb4"

[env.production]
vars = { ANALYTICS_ENABLED = "true", NEXTAUTH_URL = "https://chrisandkatie.net" }

[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "ANALYTICS"

[[env.production.d1_databases]]
binding = "DB"
database_name = "prisma-demo-db"
database_id = "73260722-51d9-4a90-961e-00d066b5dbb4"

[env.staging]
vars = { ANALYTICS_ENABLED = "false", NEXTAUTH_URL = "https://staging.chrisandkatie.net" }

[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "ANALYTICS"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "prisma-demo-db"
database_id = "73260722-51d9-4a90-961e-00d066b5dbb4"
